[project]
name = "service-xyz"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["lib-b"]

[tool.uv.sources]
lib-b = { path = "../../libs/lib-b", editable = true }

[dependency-groups]
dev = ["pytest>=8.4.1"]
